/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.algebra.view;

import hr.algebra.model.Article;
import hr.algebra.model.ArticleListModel;
import hr.algebra.parsers.rss.ArticleParser;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListModel;
import javax.xml.stream.XMLStreamException;

/**
 *
 * @author doss
 */
public class UploadPanel extends javax.swing.JPanel {

    /**
     * Creates new form UploadPanel
     */
    public UploadPanel() {
        initComponents();
        List<Article> articles = null;
        try {
            articles = ArticleParser.parse();
        } catch (IOException ex) {
            Logger.getLogger(UploadPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (XMLStreamException ex) {
            Logger.getLogger(UploadPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListModel model = new ArticleListModel(articles);
        articles.forEach(x -> System.out.println(x));
        lsArticles.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spArticles = new javax.swing.JScrollPane();
        lsArticles = new javax.swing.JList<>();
        btUpload = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lsArticles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spArticles.setViewportView(lsArticles);

        add(spArticles, java.awt.BorderLayout.CENTER);

        btUpload.setText("jButton1");
        btUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUploadActionPerformed(evt);
            }
        });
        add(btUpload, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUploadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btUploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btUpload;
    private javax.swing.JList<String> lsArticles;
    private javax.swing.JScrollPane spArticles;
    // End of variables declaration//GEN-END:variables
}
